#!/usr/bin/env python3
"""Export the decomp's core1/core2 symbols as a linker script for the mod.

    gen_syms.py <nm> <banjo.elf> <out.ld>

Only always-resident code/data is exported (boot, core1, core2, libultra):
level overlays share the same addresses with each other, so their symbols
are left out. Names that appear at two different addresses are dropped too.
"""
import subprocess
import sys


def main():
    nm, elf, out = sys.argv[1:4]
    lines = subprocess.run([nm, elf], check=True, capture_output=True, text=True).stdout.splitlines()
    syms = {}
    for line in lines:
        parts = line.split()
        if len(parts) != 3:
            continue
        addr, kind, name = int(parts[0], 16), parts[1], parts[2]
        syms.setdefault(name, set()).add((addr, kind))

    core2_end = max(a for a, _ in syms.get("core2_VRAM_END", {(0x80386460, "T")}))
    keep = {}
    for name, entries in syms.items():
        addrs = {a for a, _ in entries}
        if len(addrs) != 1:
            continue
        addr = addrs.pop()
        if not (0x80000000 <= addr < 0x80400000):
            continue
        # skip the shared level-overlay window (between core2 and the framebuffers)
        if core2_end <= addr < 0x803A5D00:
            continue
        if "." in name or name.startswith("$"):
            continue
        keep[name] = addr

    with open(out, "w") as f:
        f.write("/* Generated by tools/gen_syms.py from the decomp ELF - do not edit. */\n")
        for name in sorted(keep):
            f.write("PROVIDE(%s = 0x%08X);\n" % (name, keep[name]))
    print("exported %d symbols" % len(keep))


if __name__ == "__main__":
    main()
