#!/usr/bin/env python3
"""Convert PNG textures into N64 RGBA16 (RGBA5551) C arrays.

    png2n64.py <out.c> <out.h> <size> <name1.png> [name2.png ...]

Images of any resolution are resized (Lanczos) to <size>x<size> so they fit
TMEM; 32x32 RGBA16 is 2 KB, half of the 4 KB texture memory. Drop a
higher-resolution PNG into assets/textures/ under an existing name to
replace a part texture.
"""
import os
import sys

from PIL import Image


def to5551(r, g, b, a):
    return ((r >> 3) << 11) | ((g >> 3) << 6) | ((b >> 3) << 1) | (1 if a >= 128 else 0)


def main():
    out_c, out_h, size = sys.argv[1], sys.argv[2], int(sys.argv[3])
    pngs = sys.argv[4:]
    names = []
    with open(out_c, "w") as c:
        c.write("/* Generated by tools/png2n64.py - do not edit. */\n")
        c.write('#include "nb_textures.h"\n\n')
        for path in pngs:
            name = os.path.splitext(os.path.basename(path))[0]
            names.append(name)
            img = Image.open(path).convert("RGBA")
            if img.size != (size, size):
                img = img.resize((size, size), Image.LANCZOS)
            px = list(img.get_flattened_data() if hasattr(img, "get_flattened_data") else img.getdata())
            c.write("u16 nbTex_%s[%d] __attribute__((aligned(8))) = {\n" % (name, size * size))
            for i in range(0, len(px), 8):
                c.write("    " + ", ".join("0x%04X" % to5551(*p) for p in px[i:i + 8]) + ",\n")
            c.write("};\n\n")
        c.write("u16 *nbTextures[NB_TEX_COUNT] = {\n")
        for name in names:
            c.write("    nbTex_%s,\n" % name)
        c.write("};\n")
    with open(out_h, "w") as h:
        h.write("/* Generated by tools/png2n64.py - do not edit. */\n")
        h.write("#ifndef NB_TEXTURES_H\n#define NB_TEXTURES_H\n#include <ultra64.h>\n\n")
        h.write("#define NB_TEX_SIZE %d\n\n" % size)
        h.write("enum nb_texture_e {\n")
        for name in names:
            h.write("    TEX_%s,\n" % name.upper())
        h.write("    NB_TEX_COUNT\n};\n\n")
        h.write("extern u16 *nbTextures[NB_TEX_COUNT];\n\n#endif\n")


if __name__ == "__main__":
    main()
